name: food_app_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^7.0.8
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.0.0
  http: ^1.0.0

  #State Management Technique
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5


  # MAP
  google_maps_flutter: ^2.3.1
  geocoding: ^2.1.0
  

  # FoodApp
  path_drawing: ^1.0.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7

  clippy_flutter: ^1.1.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  random_string: ^2.3.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  firebase_app_check: ^0.3.2
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  firebase_analytics: ^11.4.0
  fluttertoast: ^8.2.10
  permission_handler: ^10.2.0
  location: ^6.0.2
  geolocator: ^13.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  http: ^0.13.0
  clippy_flutter : 2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.3.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:

  uses-material-design: true

  assets:
   - images/food/
   - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
